### ISSUE TITLE
epic: refactor account model in kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1023]
### Describe the Feature Request

context:  simplify and make future-proof the account abstraction (EOA and CA) in kakarot
currently, CAs don't have versioning, and will turn out to be hard to upgrade in the future.

```[tasklist]
### Tasks
- [ ] equalize APIs between CA and EOA -> both CA and EOA will have the same functions, i.e. __validate__, __execute__, and fetch_bytecode, set_bytecode, etc.
- [ ] CA has __validate__ and __execute__ same as EOA, add the logic of https://eips.ethereum.org/EIPS/eip-3607 -> check code is empty
- [ ] replace proxy pattern with replace_class_hash pattern
- [ ] https://github.com/kkrt-labs/kakarot/issues/1045
- [ ] https://github.com/kkrt-labs/kakarot/issues/1044
- [ ] remove the get_type() entrypoint
```
