### ISSUE TITLE
epic: support cancun hard fork

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot#1028]
### Describe the Feature Request

Support all the EVM-related EIPs included in the Cancun hard fork

- [ ] https://github.com/kkrt-labs/kakarot/issues/914
- [x] https://github.com/kkrt-labs/kakarot/issues/1000
- [x] https://github.com/kkrt-labs/kakarot/issues/1006
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/914
- [x] https://github.com/kkrt-labs/kakarot/issues/1000
- [x] https://github.com/kkrt-labs/kakarot/issues/1006
- [ ] https://github.com/kkrt-labs/kakarot/issues/1038
- [ ] https://github.com/kkrt-labs/kakarot/issues/1039
```
