### ISSUE TITLE
testnet: plan state reset + introduction of new staging environment 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1101]
Kakarot Sepolia is coming!

## Kakarot Sepolia appchain reset:
```[tasklist]
### Tasks
- [ ] Sync with SW and give green light to reset Kakarot appchain (called Kakarot Sepolia)
- [ ] Redeploy latest released Kakarot contracts to appchain + PR Kakarot repo with new deployments artifacts
- [ ] Update Karnot indexer environment variable, faucet environment variable, RPC docker-compose files
- [ ] Fund faucet private key
- [ ] Reset block explorers
```

## Kakarot Staging appchain creation:
```[tasklist]
### Tasks
- [ ] Sync with SW and give green light to start Kakarot staging (integration environment)
- [ ] Deploy latest released Kakarot contracts to appchain + PR Kakarot repo with new deployments artifacts
- [ ] Update local docker-compose staging indexer environment variable, RPC docker-compose files
- [ ] Create a staging blockscout service as block explorer
```

**Comment by ClementWalter** [comment]
@Eikix should we close?

**Comment by Eikix** [comment]
Yes
