### ISSUE TITLE
feat: add major EVM contracts in deploy_kakarot scripts

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1113]
### Describe the Feature Request

We want important EVM contracts to be deployed as part of the deployment script, e.g. WETH

```[tasklist]
### Tasks
- [ ] Add contracts in the `solidity_contracts` project, most probably in their corresponding sub project
- [ ] update the makefile to have `deploy` depends on `build-sol` as well
- [ ] update the `if EVM_ADDRESS:` branch of `deploy_kakarot` to import `deploy`
- [ ] add `dump_deployments` and `get_deployments` in `scripts/kakarot` similar to `scripts/starknet`
- [ ] add deployment like `await deploy("PlainOpcodes", "Counter")`
- [ ] dump the deployments
```

**Comment by ClementWalter** [comment]
@Eikix missing the list of contracts

**Comment by Eikix** [comment]
For now only WETH

**Comment by Eikix** [comment]
> @Eikix missing the list of contracts

And multicall3
