### ISSUE TITLE
dev: investigate the ability to deprecate and remove EIP-3074 from Kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1187]
```[tasklist]
### Tasks
- [ ] Risk of breaking: Investigate the ability to find out if a contract (with underlying Starknet latest class hash) has EIP-3074 opcodes in their opcode
- [ ] If 0 SCs -> prepare the deprecate in next upgrade
- [ ] If >0 SCs -> sync with team
```

**Comment by Eikix** [comment]
Same as https://eips.ethereum.org/EIPS/eip-7266 process

**Comment by enitrat** [comment]
@Eikix what is the "risk of breaking"? Attempts to use eip-3074 opcodes post-deprecation would just make the transaction fail.

**Comment by Eikix** [comment]
> @Eikix what is the "risk of breaking"? Attempts to use eip-3074 opcodes post-deprecation would just make the transaction fail.

Yes exactly, probably 0 risk -> 0 wallets let ppl use it anywa
