### ISSUE TITLE
epic: steps optimization

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1263]
### Describe the Feature Request

An issue to trac all sub issues related to steps optimization. See this PR for a loop profiling https://github.com/kkrt-labs/kakarot/pull/1256

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/1261
- [ ] https://github.com/kkrt-labs/kakarot/issues/1262
- [ ] https://github.com/kkrt-labs/kakarot/issues/1302
- [ ] https://github.com/kkrt-labs/kakarot/issues/1273
```

When proposing an optimization, check result by profiling the loop as in https://github.com/kkrt-labs/kakarot/pull/1256
