### ISSUE TITLE
dev: verify Kakarot on Starknet Sepolia 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1460]
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/1461
- [ ] verify Kakarot on Starknet Sepolia on Starkscan
- [ ] update to latest classhash then verify Kakarot on Starknet Mainnet on Voyager
- [ ] update to latest classhash then verify Kakarot on Starknet Mainnet on Starkscan
``` 

cc'ing @enitrat and @obatirou for further scoping

**Comment by ClementWalter** [comment]
latest supported compiler is 0.10.3 for both starkscan and voyager
<img width="400" alt="image" src="https://github.com/user-attachments/assets/69a263b1-d724-4785-91e0-aa90420e353b">
