### ISSUE TITLE
dev: modexp

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#1496]
as seen together teccak will repair modexp and make kakarot great again ♥️
```[tasklist]
### Tasks
- [ ] check modexp specification
- [ ] ignore kakarot modexp implementation and start over
- [ ] use new circuits?? on starknet to reimplement modexp soundly
- [ ] decide whether to implement modexp not for arbitrary length uints, but rather up to 256 bits
```

**Comment by tekkac** [comment]
Ahoy sir, as per seen offline, I am interested in this endeavor. I would oblige if I could get the chance to be assigned.

**Comment by enitrat** [comment]
@tekkac as a first task, a modexp version that works with inputs of size < 256 bits would be nice. I think it should be doable with Garaga.

**Comment by tekkac** [comment]
I [created a repo](https://github.com/tekkac/cairo_modexp) with two impls: u256 and u384 with circuits.
I will integrate the Circuit impl in kkrt-ssj with unit testing.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Eikix** [comment]
> I [created a repo](https://github.com/tekkac/cairo_modexp) with two impls: u256 and u384 with circuits. I will integrate the Circuit impl in kkrt-ssj with unit testing.

What do you think is your ETA on this? Can we include it in our next release early november?
In order to have code freeze before mainnet
