### ISSUE TITLE
feat: change Kakarot.eth_send_transaction (the contract function, not that library method) to not take origin as parameter, but rather get it from get_caller_address() and inject it inside the library call

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#704]
# Feature Request

**Describe the Feature Request**

change Kakarot.eth_send_transaction (the contract function, not that library method) to not take origin as parameter, but rather get it from get_caller_address() and inject it inside the library call

```[tasklist]
### Tasks
- [ ] change the API of Kakarot.send_eth_transaction to not take origin as param
- [ ] get origin from get_caller_address()
- [ ] get the evm_address of the EOA by calling get_evm_address() on the provide starknet address
- [ ] pass this evm_address into is_kakarot_account()
- [ ] make sure we verify we are inside a tx and not a call 
``` 

this will modify https://github.com/kkrt-labs/kakarot-rpc/pull/488

**Comment by Eikix** [comment]
Nvm after exploration, this does not appear prio
