### ISSUE TITLE
dev: rename custom RPC configuration NETWORK_NAME to `custom_rpc`

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#705]
```[tasklist]
### Tasks
- [x] in https://github.com/kkrt-labs/kakarot/blob/c2cceb899f57f3e33988204559309749178ca7c5/scripts/constants.py#L87
- [x] replace the name variable with an explicit name such as `custom_rpc`
- [x] update accordingly with regards to https://github.com/kkrt-labs/kakarot/pull/686
```

Related code:
```python
else:
    NETWORK = {
        "name": "",
        "rpc_url": os.getenv("RPC_URL"),
        "explorer_url": "",
        "devnet": False,
        "check_interval": float(os.getenv("CHECK_INTERVAL", 6)),
        "max_wait": float(os.getenv("MAX_WAIT", 30)),
    }
```
