### ISSUE TITLE
feat: revert the context on OOG

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#777]
### Describe the Feature Request

Returns a reverted Execution Context when running out of gas.

### Describe Preferred Solution

Check the remaining gas in each opcode and revert if required.

### Additional Context

Even though gas accounting is not accurate yet, we can revert when we face this, otherwise we often go up to Cairo VM runner out of resources.

### If the feature request is approved, would you be willing to submit a PR? Yes

/ No _(Help can be provided if you need assistance submitting a PR)_

```[tasklist]
### Tasks
- [x] OOG for stop_and_arithmetic_operations
- [ ] https://github.com/kkrt-labs/kakarot/issues/785
- [ ] https://github.com/kkrt-labs/kakarot/issues/797
- [ ] https://github.com/kkrt-labs/kakarot/issues/789
- [x] OOG for environmental_information
- [ ] https://github.com/kkrt-labs/kakarot/issues/792
- [ ] https://github.com/kkrt-labs/kakarot/issues/799
- [x] OOG for memory_operations
- [ ] https://github.com/kkrt-labs/kakarot/issues/787
- [x] OOG for sha3
- [x] OOG for system_operations
```
