### ISSUE TITLE
feat: dynamic gas accounting

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#819]
### Describe the Feature Request

We currently only handle static gas.

### Describe Preferred Solution

Implement all the dynamic gas
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/827
- [ ] https://github.com/kkrt-labs/kakarot/issues/855
- [ ] https://github.com/kkrt-labs/kakarot/issues/890
- [ ] https://github.com/kkrt-labs/kakarot/issues/887
- [ ] https://github.com/kkrt-labs/kakarot/issues/918
- [ ] https://github.com/kkrt-labs/kakarot/issues/930
 - [ ] https://github.com/kkrt-labs/kakarot/issues/903
```

**Comment by mostafalarki1368mos** [comment]
@ClementWalter @bajpai244 @0xMentorNotAPseudo @danilowhk @danilowhk @l-henri @l-henri @ftupas @spapinistarkware @bbrandtom @abdelhamidbakhta @AvihuLevy @louisguthmannStarkWare - @enitrat @enitrat @lana-shanghai @pscott @mnekx @dragan2234 @ArnaudBD @gaetbout @
