### ISSUE TITLE
refactor: EOA validate and execute receives a separate encoded tx calldata and signature (in tx_info)

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#829]
### Describe the Feature Request

- Currently the EOA receives a payload of eth_sendRawTransaction -> it has to: RLP::decode, extract sig, RLP::encode the calldata without sig, hash initial encoded payload, check signature, then validate.

### Describe Preferred Solution

```[tasklist]
### Tasks
- [ ] Pretend that the payload received in KKT0 is the RLP-encoded calldata of an Ethereum transaction (without the signature)
- [ ] Hash that RLP-encoded calldata, and use the tx_info.signature to do the ecdsa check
- [ ] Decode the RLP-encoded calldata, perform checks (nonce and chain_id)
- [ ] Validate
- [ ] In execute, RLP-decode and call Kakarot eth_send_transaction
``` 

### Additional Context

Check out Kakarot SSJ implementation:
https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/contracts/src/eoa.cairo

### If the feature request is approved, would you be willing to submit a PR? Yes

/ No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Eikix** [comment]
Oops duplicated here
https://github.com/kkrt-labs/kakarot/issues/831
