### ISSUE TITLE
refactor: change EOA api to take an encoded eth transaction (without its signature), and gets the signature from the tx_info field

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#831]
### Describe the Feature Request

In kakarot SSJ we decided to refactor slightly the EOA to take an encoded tx without its signature being encoded inside too. c.f. https://github.com/kkrt-labs/kakarot-ssj/issues/276

### Describe Preferred Solution

- signature is now taken from tx_info field
- the encoded payload is the "full tx" -> can directly hash it and check ecdsa signature
- then, decode the tx and check important stuff -> nonce, chain id, parity?

Then g2g!
Changes: no more encoding!

```[tasklist]
### Tasks
- [ ] Get signature from tx_info field
- [ ] Hash the encoded payload first and check signature
- [ ] Then decode it and check invariants
- [ ] In __execute__, change the decode logic -> you're now decoding a simpler payload
```
