### ISSUE TITLE
epic: clean code, update utils, u256 casting and felt and increase consistency in codebase 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#833]
### Describe the Feature Request

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/835
- [x] replace gas_limit and gas_used by gas_remaining
- [ ] https://github.com/kkrt-labs/kakarot/issues/845
- [ ] https://github.com/kkrt-labs/kakarot/issues/851
- [ ] https://github.com/kkrt-labs/kakarot/issues/855
```

**Comment by mostafalarki1368mos** [comment]
**_**[]()[]()![Transactions_1402_10_17_11_24.xlsx](https://github.com/kkrt-labs/kakarot/files/13853618/Transactions_1402_10_17_11_24.xlsx)
