### ISSUE TITLE
feat: make chain_id an environmental variable (injected by Starknet in the Environment data structure at transaction time) 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#848]
### Describe the Feature Request

Copy of https://github.com/kkrt-labs/kakarot-ssj/issues/641

```[tasklist]
### Tasks
- [x] Refactor `chain_id` variable to come from syscall (backend object) at the beginning of a call to Kakarot, into the Environment object. Check with ef-tests team that this is okay for them in terms of updates
- [x] Refactor tests
- [x] Refactor CHAINID opcode to grab the chainid from the environment
- [x] Refactor the EOA to not rely on a hardcoded chain_id but on the underlying chain id of the network
```

**Comment by ClementWalter** [comment]
note: EOA and Kakarot use the same CHAIN_ID constant in the code, though eventually the contracts are deployed and there is no more link in between them
