### ISSUE TITLE
epic: Precompiles

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot#856]
Precompiles miscellaneous issues in the current codebase.

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/1230
- [ ] https://github.com/kkrt-labs/kakarot/issues/1231
- [ ] https://github.com/kkrt-labs/kakarot/issues/364
- [ ] https://github.com/kkrt-labs/kakarot/issues/1233
```
