### ISSUE TITLE
dev: remove deploy_fee, and deploy_fee concept in Kakarot applicative code

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#869]
```[tasklist]
### Tasks
- [ ] In deploy_externally_owned_account in kakarot library, remove the concept that the deployed EOA pays the caller for the deploy fee
- [ ] Remove the deploy fee storage var
- [ ] Remove the deploy fee getter
- [ ] Remove mentions of the deploy fee in test suite
``` 

The idea behind the deploy fee was that the Kakarot infra could hold a pk and deploy EOA accounts for users, and the accounts would then reimburse the deployer of the EOA with their funds.
This is highly impractical because at the moment, this means one must fund in native token an address (starknet address) before deploying it as an EOA.

I recommend removing completely this logic, as for our testnet, accounts will be deployed by a service for users
