### ISSUE TITLE
dev: improve the starknet test runner

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#889]
PR #873 introduced a fast `cairo_run` fixture to run test again plain cairo program and not the whole starknet testing object.

This however doesn't allow to run fast test using syscalls and a starknet state.

Because Kakarot indeed only uses syscalls to read and write data if not present in the current `model.State`, there should be a way to initialize the `State` with a hint and never use these syscalls, and preventing from the need to have syscalls.
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/pull/896
- [ ] https://github.com/kkrt-labs/kakarot/issues/916
- [ ] https://github.com/kkrt-labs/kakarot/issues/919
- [ ] https://github.com/kkrt-labs/kakarot/issues/928
```
