### ISSUE TITLE
EIP1559

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#891]
### Describe the Feature Request

Support EIP1559 tx, see https://eips.ethereum.org/EIPS/eip-1559

Currently, we support them in the sense that we can decode and run them, but using `max_fee_per_gas` as `gas_price`.

However, the actual gas price should be

```
# priority fee is the min betwee user max price - block price (the implicit priority fee paid given user max price input) and the explicit max priority fee set
priority_fee_per_gas = min(
        transaction.max_priority_fee_per_gas,
        transaction.max_fee_per_gas - block.base_fee_per_gas
)

# final price is block base price + priority fee
effective_gas_price = priority_fee_per_gas + block.base_fee_per_gas
```

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/929
- [x] Add a view entrypoint to query the basefee and coinbase
- [x] Add a permissionned set_basefee / set_coinbase
```
