### ISSUE TITLE
Add a serde utils for any cairo struct

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot#919]
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/939
- [ ] https://github.com/kkrt-labs/kakarot/issues/940
- [ ] https://github.com/kkrt-labs/kakarot/issues/941
- [ ] https://github.com/kkrt-labs/kakarot/issues/942
```
