### ISSUE TITLE
devops: audit deployer dockerfile to understand why the image is 1.2gb

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#962]
Context:
Kakarot docker/deployer/Dockerfile is necessary for Kakarot RPC, it's a script to deploy Kakarot on an underlying CairoVM chain.

Kakarot deployer image is 1.2gb! I checked, and:
- python deps are 300mb
- files are <5mb 

Where are the missing 800mb?

```[tasklist]
### Tasks
- [ ] Profile the Kakarot deployer image (using Dockerslim or Docker Dive)
- [ ] Understand why the image is so heavy
- [ ] Optimize if possible
```

**Comment by khaeljy** [comment]
Maybe I can check this ;)

**Comment by khaeljy** [comment]
By analyzing the image with `dive`, I notice that there are 2 layers that significantly magnify the final image:

1. Package installation (325 MB)
https://github.com/kkrt-labs/kakarot/blob/e50c72acd55be20d84b98cf9fbf6d8f02656d63a/docker/deployer/Dockerfile#L42-L50
2. Installation of poetry dependencies (780 MB)
https://github.com/kkrt-labs/kakarot/blob/e50c72acd55be20d84b98cf9fbf6d8f02656d63a/docker/deployer/Dockerfile#L59

<img width="821" alt="image" src="https://github.com/kkrt-labs/kakarot/assets/1810456/c8bee784-59b7-449b-867e-293ec9200f26">

**Comment by khaeljy** [comment]
Here is the list of files added/modified when installing poetry dependencies:
<img width="947" alt="image" src="https://github.com/kkrt-labs/kakarot/assets/1810456/e7a5a79a-4471-463f-88f3-aad6ce254b22">

Can we limit which dependencies are really useful for running `deploy_kakarot.py` (perhaps with [dependency groups](https://python-poetry.org/docs/master/managing-dependencies/))? 
Is it possible to delete the poetry cache directory?

**Comment by Eikix** [comment]
@ClementWalter what do you think?
This is for the kakarot deployer docker image

**Comment by ClementWalter** [comment]
We could also remove poetry for the image and use plain pip, or even the new https://astral.sh/
