### ISSUE TITLE
bug: eth_call should be able to take in as parameter an arbitrary nonce

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#996]
### Current behavior

currently, when someone uses `Kakarot.eth_call`, for `estimate_gas` and `eth_call`, the nonce of that tx is hard set to be 0 because of starknet_call's tx_info.nonce field being always 0 (for txs, this is the procotol nonce, but for calls, it's 0)

this breaks eth_call expected behaviour

```[tasklist]
### Tasks
- [ ] add nonce parameter to eth_call, note a nonce can be a simple field since the value is capped at u64::max
- [ ] 🚧 nonce in eth_send_transaction remains the tx_info.nonce for now!
- [ ] modify tests and fixtures in test-end-to-end
```
