### ISSUE TITLE
dev: bump katana, starknet_py and adopt rpc spec 0.6 in all python scripts

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot#998]
```[tasklist]
### Tasks
- [x] bump katana to 0.6 alpha. 1 or 2
- [x] bump starknet py to 0.20
- [ ] adapt scripts to adopt rpc spec 0.6
```
